version: '3.8'
volumes:
  postgres_data:
  static_volume:
  media_volume:
  
services:
  web:
    # build: ./
    image: ivanfr1025/final-work-1025-ivanfr:web-final
    command: gunicorn django_app.wsgi:application --bind 0.0.0.0:8000
    # command: sh -c "python manage.py migrate && python manage.py createsuperuser --noinput && gunicorn django_app.wsgi:application --bind 0.0.0.0:8000"
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
    volumes:
      # - static_volume:/home/app/web/staticfiles
      - ./:/usr/src/app/
      - ./static/:/usr/src/app/static/
      - ./media/:/usr/src/app/media/
    # ports:
    #   - 8000:8000
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
 
  nginx:
    # build: ./nginx
    image: ivanfr1025/final-work-1025-ivanfr:nginx-final
    volumes:
      - ./static/:/usr/src/app/static/
      - ./media/:/usr/src/app/media/
    ports:
      - 8008:80
    depends_on:
      - web
 
  db:
    image: postgres:15.3
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    # expose:
    #   -5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=django_app_dev
